<a href="https://colab.research.google.com/github/Test-SH-1/Test-/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dummy code

In [4]:
import pandas as pd

# Google Sheet ID from your URL
sheet_id = "1E7r3sZwYqEGFhYJDTT4k1is7nmZCkCw2GMpNy-im538"

# Sheet tab name
sheet_name = "Sheet1"

# Read the Google Sheet as a CSV
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

df = pd.read_csv(url)

print("Original data:")
display(df)

# Example calculations
df["Total Cost"] = (
    df["Research"]
    + df["Travel"]
    + df["Software"]
)

df["Cost + 10% Contingency"] = df["Total Cost"] * 1.10

print("Calculated data:")
display(df)

# Summary
print("Total project cost:", df["Total Cost"].sum())
print("Average monthly cost:", df["Total Cost"].mean())
print(
    "Total cost including 10% contingency:",
    df["Cost + 10% Contingency"].sum()
)

Original data:

      Month  Research  Travel  Software
0   January     12000    5000      2000
1  February     15000    3000      2000
2     March     11000    7000      2500
3     April     16000    4000      2500
4       May     14000    6000      3000

Calculated data:

      Month  Research  Travel  Software  Total Cost  Cost + 10% Contingency
0   January     12000    5000      2000       19000                 20900.0
1  February     15000    3000      2000       20000                 22000.0
2     March     11000    7000      2500       20500                 22550.0
3     April     16000    4000      2500       22500                 24750.0
4       May     14000    6000      3000       23000                 25300.0

Total project cost: 105000
Average monthly cost: 21000.0
Total cost including 10% contingency: 115500.0